spring:
    datasource:
        name: test
        url: jdbc:mysql://192.168.1.241:3306/didibuy?useUnicode=true&autoReconnect=true&rewriteBatchedStatements=true
        username: didibuy
        password: didibuy123
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        druid:
            filters: wall,stat
            max-active: 50
            initial-size: 10
            max-wait: 60000
            minIdle: 1
            time-between-eviction-runs-millis: 60000
            min-evictableIdle-time-millis: 300000
            validation-query: select 'x'
            test-whileIdle: true
            test-on-borrow: false
            test-on-return: false
            pool-prepared-statements: true
            max-open-prepared-statements: 20
            remove-abandoned: true
            remove-abandoned-timeout: 1800
            log-abandoned: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.iphotowalking.business.mybatis.model
#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql

