server:
  port: 7076
spring:
  application:
    name: service-zuul
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:7070/eureka/

zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: service-ribbon
    api-b:
      path: /api-b/**
      serviceId: service-feign